#!/bin/bash
echo "Tunning kernel variables…"
sysctl -w net.ipv4.igmp_max_memberships=200 > /dev/null
sysctl -w net.ipv4.ip_forward=1 > /dev/null
sysctl -w net.ipv4.conf.default.rp_filter=0 > /dev/null
sysctl -w net.ipv4.conf.all.accept_redirects=0 > /dev/null
sysctl -w net.ipv4.conf.all.rp_filter=0 > /dev/null
sysctl -w net.ipv4.conf.default.force_igmp_version=2 > /dev/null
sysctl -w net.ipv6.conf.all.forwarding=2 > /dev/null
echo "Stopping interfaces…"
ip link set enp1s0f0 down
ip link set enp1s0f1 down
ip link set wlp0s20u10 down
ip link delete data 2> /dev/null
ip link delete tv 2> /dev/null
ip link delete vod 2> /dev/null
ip link delete tv 2> /dev/null
ip link delete lxcbr0 2> /dev/null
ip link delete gre31 2> /dev/null
ip link delete gre32 2> /dev/null
ip link delete local 2> /dev/null
ip address flush enp3s0
ip address flush enp1s0f0
ip address flush enp1s0f1
ip address flush wlp0s20u10
ip -6 address flush enp3s0
ip -6 address flush enp1s0f0
ip -6 address flush enp1s0f1
ip -6 address flush wlp0s20u10
ip route flush all
ip -6 route flush all
echo "Creating interfaces…"
ip link add link enp1s0f0 name data type vlan id 832 egress-qos-map 0:6 1:0 2:2 3:3 4:4 5:5 6:6 7:7
ip link add link enp1s0f0 name tv type vlan id 838 egress-qos-map 0:4 1:4 2:4 3:4 4:4 5:4 6:4 7:4
ip link add link enp1s0f0 name vod type vlan id 840 egress-qos-map 0:5 1:5 2:5 3:5 4:5 5:5 6:5 7:5
ip link add local type bridge
ip link add lxcbr0 type bridge
ip link set enp1s0f1 master local
ip link set wlp0s20u10 master local
ip link set enp3s0 master local
ip address add 10.2.0.254/16 dev local
ip address add 192.168.255.252/32 dev data
ip address add 192.168.255.253/32 dev tv
ip address add 192.168.255.254/32 dev vod
ip address add 172.16.0.1/16 dev lxcbr0
ip link set enp3s0 up
ip link set enp1s0f0 up
ip link set enp1s0f1 up
ip link set wlp0s20u10 up
ip link set tv up
ip link set data up
ip link set lxcbr0 up
ip link set local up
echo "Creating tunnels…"
ip tunnel add gre31 mode gre remote 163.172.26.137 dev data
ip address add 10.40.3.1/32 dev gre31
ip link set dev gre31 mtu 1472
ip link set gre31 up
ip route add 10.40.1.3/32 dev gre31
ip route add 10.0.0.0/16 dev gre31
ip tunnel add gre32 mode gre remote 163.172.36.148 dev data
ip address add 10.40.3.2/32 dev gre32
ip link set dev gre32 mtu 1472
ip link set gre32 up
ip route add 10.40.2.3/32 dev gre32
ip route add 10.1.0.0/16 dev gre32
echo "Stopping services…"
systemctl stop ipv4
systemctl stop ipv6
systemctl stop radvd
systemctl stop igmp
systemctl stop iptables
systemctl stop dhcpd
systemctl stop ntpd
systemctl stop hostapd
echo "Restoring firewall…"
systemctl start iptables
echo "Retrieving IPv4 public address…"
systemctl start ipv4
echo "Wating IPv4 connectivity…"
while true; do
	ping -c1 8.8.8.8 > /dev/null 2> /dev/null && break
done;
echo "Starting DHCP server…"
systemctl start dhcpd
echo "Starting NTP server…"
systemctl start ntpd
echo "Starting IGMP proxy…"
systemctl start igmp
echo "Starting WiFi antenna…"
systemctl start hostapd
echo "Retrieving IPv6 prefix…"
systemctl start ipv6
echo "Wating IPv6 connectivity…"
while true; do
  ping6 -c1 2001:4860:4860::8888 > /dev/null 2> /dev/null && break
done;
echo "Starting SLAAC server…"
systemctl start radvd
echo "Send IP addresses to DNS server…"
systemctl start sendip
